# Generated by Django 6.0 on 2025-12-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanogen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='source_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
