# Generated by Django 6.0 on 2025-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanogen', '0002_sourceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidjourneyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('styles', 'Style / Look'), ('global_details', 'Global Details'), ('expression', 'Expression'), ('camera_angle', 'Camera Angle'), ('characteristics', 'Characteristics'), ('pose', 'Pose'), ('action', 'Action'), ('lighting', 'Lighting'), ('atmosphere', 'Atmosphere'), ('character_details', 'Character Details'), ('env_details', 'Environmental Details')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'label'],
            },
        ),
    ]
